// src/App/Pages/Console/Console.vue
<template>
  <section class="console">
    <ConsoleHeader />
    <ConsoleReqHistory />
    <ConsoleBody />
    <ConsoleFooter />
    <ConsoleWindowLoader />
    <ConsoleModalWindow />
  </section>
</template>

<script>
  import ConsoleHeader from './ConsoleHeader'
  import ConsoleReqHistory from './ConsoleReqHistory'
  import ConsoleBody from './ConsoleBody'
  import ConsoleFooter from './ConsoleFooter'
  import ConsoleWindowLoader from './ConsoleWindowLoader'
  import ConsoleModalWindow from '../../UI/ConsoleModalWindow/ConsoleModalWindow'

  export default {
    components: {
      ConsoleHeader, 
      ConsoleReqHistory,
      ConsoleBody,
      ConsoleFooter,
      ConsoleWindowLoader,
      ConsoleModalWindow
    },
    
  }
</script>

// src/App/Pages/Console.jsx
import React, { useRef } from 'react';
import ConsoleHeader from '../Components/ConsoleHeader';
import ConsoleReqHistory from '../Components/ConsoleReqHistory';
import ConsoleBody from '../Components/ConsoleBody';
import ConsoleFooter from '../Components/ConsoleFooter';
import ConsoleWindowLoader from '../Components/ConsoleWindowLoader';
import ConsoleModalWindow from './../Components/ConsoleModalWindow';

const Console = () => {
  const el = useRef(null);

  return(
    <section className="console" ref={el}>
      <ConsoleHeader el={el} />
      <ConsoleReqHistory />
      <ConsoleBody />
      <ConsoleFooter />
      <ConsoleWindowLoader />
      <ConsoleModalWindow/>
    </section>
  )
}

export default Console;
