// src/App/Pages/Console/Components/ConsoleFooter/ConsoleFooter.vue
<template>
  <div class="console__footer footer console_block">
    <SubmitButton />
    <a href="https://github.com/chetvertkoff/sendsay" class="link footer__link">@chetvertkoff</a>  
    <FormatButton />
  </div>
</template>

<script>
  import SubmitButton from './Components/SubmitButton'
  import FormatButton from './Components/FormatButton'

  export default {
    components: {SubmitButton, FormatButton}
  }
</script>

// src/App/Components/Console/Footer/ConsoleFooter.jsx
import React from 'react';
import FormatButton from './FormatButton';
import SubmitButton from './SubmitButton';

const ConsoleFooter = () => {

  return (
    <div className="console__footer footer console_block">
      <SubmitButton />
      <a href="https://github.com/chetvertkoff/sendsay" className="link footer__link">@chetvertkoff</a>  
      <FormatButton />
    </div>
  );
}

export default ConsoleFooter;
