// src/App/Pages/Console/SubmitButton.vue
<template>
  <Button 
    :title="'Отправить'" 
    :classes="['footer__button']"
    :isLoad="isLoad"
    @on-click="submitReq"
  />
</template>

<script>
  import { mapState } from 'vuex'
  import Button from '@/UI/Button'
  import Validate from '@/utils/Validate'
  import logout from '@/utils/logout'
  
  export default {
    components: {Button},
    computed: mapState({
      reqData: state => state.consoleRequest.reqData,
      reqErr: state => state.consoleRequest.reqErr,
      isLoad: state => state.consoleRequest.loading
    }),
    methods: {
      submitReq() {
        const isValidRequest = Validate.isValidRequest(this.reqData);

        if(!isValidRequest){
          this.$store.dispatch('setReqErr', true);
          return;
        }
        if(this.reqErr) this.$store.dispatch('setReqErr', false);
        
        this.sendReqDataAsync();
      },
      async sendReqDataAsync() {
        const res = await this.$store.dispatch('sendReqData', this.reqData);
        if(res == "logout") logout();
      }
    }
  }
</script>

// src/App/Components/Console/Footer/SubmitButton.jsx
import React  from 'react';
import { useDispatch, useSelector } from '../../../../react-redux/';
import useAuth from '../../../hooks/useAuth';
import { sendReqData } from '../../../Store/Action/consoleRequest';
import Validate from '../../../utils/validate';
import Button from './../../UI/Button';

const SubmitButton = () => {
  const {logOut} = useAuth();
  const dispatch = useDispatch();
  const reqErr = useSelector(state => state.consoleRequest.reqErr);
  const reqData = useSelector(state => state.consoleRequest.reqData);
  const loading = useSelector(state => state.consoleRequest.loading);
  
  const sendReqDataAsync = async () =>{
    const res = await dispatch(sendReqData(reqData));
    if(res == "logout") logOut();
  }

  const submitReq = () => {
    const isValidRequest = Validate.isValidRequest(reqData);

    if(!isValidRequest){
      dispatch({type:'REQ_ERR', payload: true});
      return;
    }
    if(reqErr) dispatch({type:'REQ_ERR', payload: false});
    
    sendReqDataAsync();
  }

  return (
    <Button 
      loading={loading} 
      onClick={submitReq} 
      title="Отправить" 
      classes={['footer__button']}
    />
  );
}

export default SubmitButton;
