// src/App/Pages/Console/Components/ConsoleHeader.vue
<template>
  <div class="console__header console_block">
    <Logo :parentClass="'console__logo'"/>
    <h3 class="console__logo-title">API-консолька</h3>
    <div class="console__user-email">
      <span>{{userInfo.login}}</span>
      <span v-if="userInfo.login && userInfo.sublogin" class="console__delimiter">:</span>
      <span>{{userInfo.sublogin}}</span>
    </div>
    <button class="console__logout-button" @click="logOut">
      Выйти 
      <svg class="icon">
        <use xlink:href="/assets/icon/sprite.svg#log-out"></use>
      </svg>
    </button>
    <div class="console__fullscreen-button" @click="toggleFullscreen">
      <svg class="icon">
        <use 
          :xlink:href="`/assets/icon/sprite.svg#fullscreen-${isFullscreen ? 'on' : 'off' }`"
        ></use>
      </svg>
    </div>
  </div>
</template>

<script>
  import Logo from '@/UI/Logo'
  import logout from '@/utils/logout'
  import fscreen from 'fscreen'

  export default {
    components: {Logo},
    data() {
      return {
        userInfo: {login:'', sublogin: ''},
        isFullscreen: false
      }
    },
    methods: {
      logOut() {
        logout()
         .then(() => this.$router.push('/login'))
      },
      toggleFullscreen() {
        const el = this.$parent.$el;
        
        if(!fscreen.fullscreenElement){
          fscreen.requestFullscreen(el);
        }else{
          fscreen.exitFullscreen();
        }
      },
      fullScreenEvent() {
        this.isFullscreen = !!fscreen.fullscreenElement;
      }
    },
    created() {
      this.userInfo = JSON.parse(localStorage.getItem('user_info'));
      fscreen.addEventListener('fullscreenchange', this.fullScreenEvent);
    },
    destroyed() {
      fscreen.removeEventListener('fullscreenchange', this.fullScreenEvent);
    }
  }
</script>

// src/App/Components/ConsoleHeader.jsx
import fscreen from 'fscreen';
import React, { useCallback, useEffect, useState } from 'react';
import useAuth from '../hooks/useAuth';
import Logo from './Logo';

const ConsoleHeader = props => {
  
  const [isFullscreen, setFullScreen] = useState(false);
  const {logOut} = useAuth();
  const {login, sublogin} = JSON.parse(localStorage.getItem('user_info'));

  useEffect(()=>{
    const fullScreenEvent = () => {
      setFullScreen(!!fscreen.fullscreenElement);
    }
    fscreen.addEventListener('fullscreenchange', fullScreenEvent);
    return ()=>{
      fscreen.removeEventListener('fullscreenchange', fullScreenEvent);
    }
  },[]);

  const toggleFullscreen = useCallback(() => {
    const el = props.el.current;
    if(!fscreen.fullscreenElement){
      fscreen.requestFullscreen(el);
    }else{
      fscreen.exitFullscreen();
    }
  },[]);

  return (
    <div className="console__header console_block">
      <Logo parentClass="console__logo"/>
      <h3 className="console__logo-title">API-консолька</h3>
      <div className="console__user-email">
        <span>{login}</span>
        {login && sublogin && <span className="console__delimiter">:</span>}
        <span>{sublogin}</span>
      </div>
      <button className="console__logout-button" onClick={logOut}>
        Выйти 
        <svg className="icon">
          <use xlinkHref="/assets/icon/sprite.svg#log-out"></use>
        </svg>
      </button>
      <div className="console__fullscreen-button" onClick={toggleFullscreen}>
        <svg className="icon">
          <use 
            xlinkHref={`/assets/icon/sprite.svg#fullscreen-${isFullscreen ? "on" : "off" }`}
          ></use>
        </svg>
      </div>
    </div>
  );
}

export default ConsoleHeader;
