// src/App/Pages/Console/Components/ConsoleReqHistory/ConsoleReqHistory.vue
<template>
  <div class="console__req-history console_block">
    <ul 
      class="console__req-list" 
      :class="{'console__req-list_dropped': currentId != null}"
      @click="setDrop"
      @wheel="scroll"
    >
      <template v-for="(el, i) in reqHistoryData">
        <ConsoleReqHistoryItem 
          :key="i" 
          :itemId="i"
          :item="el"
          :showDrop="currentId == i"
        />
      </template>
    </ul>
    <ConsoleClearButton v-if="reqHistoryData.length" />
  </div>
</template>

<script>
  import { mapGetters, mapState } from 'vuex';
  import ConsoleReqHistoryItem from './Components/ConsoleReqHistoryItem'
  import ConsoleClearButton from './Components/ConsoleClearButton'

  export default {
    components: {ConsoleReqHistoryItem, ConsoleClearButton},
    data() {
      return {
        currentId: null,
        reqHistory: null
      }
    },
    computed: {
      ...mapGetters(['reqHistoryData'])
    },
    methods: {
      setDrop(e) {
        const id = e.target.id;

        if(!id || id == this.currentId) {
          this.currentId = null;
          return;
        }
        this.currentId = id;
      },
      handleClickOutside(e) {
        if(this.currentId == null) return;

        if (!this.$el.contains(e.target)) {
          this.currentId = null;
        }
      },
      scroll(e = {}) {
        if(this.currentId) return;
    
        let item = e.currentTarget || null;
        const optionsUI = JSON.parse(localStorage.getItem('optionsUI')) || {};
        if(!optionsUI.scrollPos) optionsUI.scrollPos = 0;

        if(!item){
          item = this.$el;
        }else{
          const {scrollWidth, scrollLeft, offsetWidth} = item;
          const pos = scrollWidth-scrollLeft-offsetWidth;

          if (e.deltaY > 0) optionsUI.scrollPos += 100;
          else optionsUI.scrollPos -= 100;
          if(pos < 1) optionsUI.scrollPos -= 100;
          if(optionsUI.scrollPos <= 0) optionsUI.scrollPos = 0;
        }
        item.scrollLeft = optionsUI.scrollPos;
        localStorage.setItem('optionsUI', JSON.stringify({...optionsUI, scrollPos: optionsUI.scrollPos}));
      }
    },
    mounted() {
      this.scroll();
      document.addEventListener("click", this.handleClickOutside);
    },
    destroyed() {
      document.removeEventListener("click", this.handleClickOutside);
    }
  }
</script>

// src/App/Components/ConsoleReqHistory.jsx
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { connect } from 'react-redux';
import ConsoleReqHistoryItem from './ConsoleReqHistoryItem';
import ConsoleClearButton from './UI/ConsoleClearButton';

const ConsoleReqHistory = (props) => {
  const [currentId, setID] = useState(null);
  const el = useRef(null);
  const droppedClasses = ['console__req-list'];

  if(currentId != null) droppedClasses.push('console__req-list_dropped');
  else droppedClasses.filter(el=>el!=='console__req-list_dropped');

  const scroll = useCallback((e = {}) => { 
    if(currentId != null) return;
    
    let item = e.currentTarget || null;
    const optionsUI = JSON.parse(localStorage.getItem('optionsUI')) || {};
    if(!optionsUI.scrollPos) optionsUI.scrollPos = 0;

    if(!item){
      item = el.current;
    }else{
      const {scrollWidth, scrollLeft, offsetWidth} = item;
      const pos = scrollWidth-scrollLeft-offsetWidth;

      if (e.deltaY > 0) optionsUI.scrollPos += 100;
      else optionsUI.scrollPos -= 100;
      if(pos < 1) optionsUI.scrollPos -= 100;
      if(optionsUI.scrollPos <= 0) optionsUI.scrollPos = 0;
    }
    item.scrollLeft = optionsUI.scrollPos;
    localStorage.setItem('optionsUI', JSON.stringify({...optionsUI, scrollPos: optionsUI.scrollPos}));
  },[currentId]);


  const setDrop = useCallback(e=>{
    const id = e.target.id;
    if(!id || id == currentId) {
      setID(null);
      return;
    }
    setID(id);
  },[currentId])

  useEffect(()=>{
    scroll();

    const handleClickOutside = e => {
      if (!el.current.contains(e.target)) {
        setID(null);
      }
    }
    document.addEventListener("click", handleClickOutside);

    return () => {
      document.removeEventListener("click", handleClickOutside);
    };
  },[]);

  return (
    <div className="console__req-history console_block">
      <ul 
        className={droppedClasses.join(' ')}
        onWheel={scroll}
        onClick={setDrop}
        ref={el}
      >
      {[...props.reqHistory].reverse().map((el, i) =>{
        return <ConsoleReqHistoryItem 
          key={i} 
          i={i} 
          item={el} 
          showDrop={i == currentId} 
        />
      })}
      </ul>
      {props.reqHistory?.length && <ConsoleClearButton /> }
    </div>
  );
}

const mapStateToProps = state => ({
  reqHistory: state.consoleReqHistory.reqHistory
})

export default connect(mapStateToProps, null)(ConsoleReqHistory);
