// src/App/Pages/Console/Components/ConsoleReqHistory/ConsoleReqHistoryItem/ConsoleReqHistoryItem.vue
<template>
  <li class="console__req-item req-item">
    <div 
      :class="['req-item__inner', item.isErr ? 'req-item__inner_err' : 'req-item__inner_success']"
    >
      {{item.action}}
    </div>
    <svg 
      class="icon req-item__drop-icon" 
      :id="itemId"
    >
      <use xlink:href="/assets/icon/sprite.svg#req-item-drop"></use>
    </svg>
    <ReqDropCard v-if="showDrop" />
  </li>
</template>

<script>
  import ReqDropCard from './Components/ReqDropCard'
  
  export default {
    props: {
      itemId: Number,
      item: Object,
      showDrop: Boolean
    }
  }
</script>

// src/App/Components/ConsoleReqHistoryItem.jsx
import React, { useState } from 'react';

const ConsoleReqHistoryItem = ({i}) => {
  const [showDrop, setDrop] = useState(false);

  return (
    <li className="console__req-item req-item console__req-item_success">
      {i}
      track.get
      <svg className="icon console__drop-icon">
        <use xlinkHref="/assets/icon/sprite.svg#req-item-drop"></use>
      </svg>
    </li>
  );
}

export default ConsoleReqHistoryItem;
