// src/App/Pages/Console/Components/ConsoleReqHistory/Components/ConsoleReqHistoryItem.vue
<template>
  <li class="console__req-item req-item">
    <div 
      :class="[
        'req-item__inner', 
        item.isErr ? 'req-item__inner_err' : 'req-item__inner_success',
        copyClass
      ]"
      @click="fillReqField"
    >
      {{item.action}}
    </div>
    <svg 
      class="icon req-item__drop-icon" 
      :id="itemId"
    >
      <use xlink:href="/assets/icon/sprite.svg#req-item-drop"></use>
    </svg>
    <ReqDropCard 
      v-if="showDrop" 
      @copy="copy"
      @fulfilReq="fulfilReq"
      @deleteReqItem="deleteReqItem"
    />
  </li>
</template>

<script>
  import ReqDropCard from './Components/ReqDropCard'
  
  export default {
    components: {ReqDropCard},
    props: {
      itemId: Number,
      item: Object,
      showDrop: Boolean
    },
    data() {
      return {
        copyClass: ''
      }
    },
    methods: {
      copyText() {
        const copyReq = JSON.stringify({...this.item, isErr: undefined});
        const el = document.createElement("input");
        el.style.height = '0px';
        el.style.width = '1px';
        document.body.appendChild(el);
        el.value = copyReq;
        el.select();
        document.execCommand("copy");
        document.body.removeChild(el);
      },
      copy() {
        this.copyClass = 'req-item__inner_copied';
        this.copyText();

        setTimeout(() => {
          this.copyClass = '';
        }, 500);
      },
      fulfilReq() {
        console.log('fulfilReq');
      },
      fillReqField() {
        const formattedText = JSON.stringify({action: this.item.action}, null, 2);
        this.$store.dispatch('setReqData', formattedText);
        return formattedText;
      },
      deleteReqItem() {
        console.log('deleteReqItem');
      }
    }
  }
</script>

// src/App/Components/ConsoleReqHistoryItem.jsx
import React, { useCallback, useEffect, useState } from 'react';
import { connect } from 'react-redux';
import useAuth from '../hooks/useAuth';
import { deleteReqHistoryItem } from '../Store/Action/consoleReqHistory';
import { getReqData, sendReqData } from '../Store/Action/consoleRequest';
import ReqDropCard from './UI/ReqDropCard';

const ConsoleReqHistoryItem = props => {
  const item = props.item;
  const classIndicator = item.isErr ? "req-item__inner_err" : "req-item__inner_success";
  let classes = ['req-item__inner', classIndicator];
  const [copyClass, setClass] = useState('');
  const {logOut} = useAuth();


  const copyText = () => {
    const copyReq = JSON.stringify({...item, isErr: undefined});
    const el = document.createElement("input");
    el.style.height = '0px';
    el.style.width = '1px';
    document.body.appendChild(el);
    el.value = copyReq;
    el.select();
    document.execCommand("copy");
    document.body.removeChild(el);
  }

  const copy = () => {
    setClass('req-item__inner_copied');
    copyText();
    setTimeout(() => {
      setClass('');
    }, 500);
  }

  const deleteReqItem = ()=>{
    props.deleteReqHistoryItem(item.actionId);
  }

  const fulfilReq = useCallback(()=>{
    const req = fillReqField();
    sendReqData(req);
  },[]);

  const fillReqField = useCallback(()=>{
    const formattedText = JSON.stringify({action: item.action}, null, 2);
    props.getReqData(formattedText);
    return formattedText;
  },[]);

  const sendReqData = async (req) =>{
    const res = await props.sendReqData(req);
    if(res == "logout") logOut();
  }

  return (
    <li 
      className="console__req-item req-item"
    >
      <div className={[...classes, copyClass].join(' ')} onClick={fillReqField}>
        {item.action}
      </div>
      <svg 
          className="icon req-item__drop-icon" 
          id={props.i}
        >
        <use xlinkHref="/assets/icon/sprite.svg#req-item-drop"></use>
      </svg>
      {
        props.showDrop && 
          <ReqDropCard 
            copy={copy} 
            fulfilReq={fulfilReq} 
            deleteReqItem={deleteReqItem} 
          />
      }
    </li>
  );
}

const mapDispatchToProps = dispatch => ({
  getReqData: val=>dispatch(getReqData(val)),
  sendReqData: val=>dispatch(sendReqData(val)),
  deleteReqHistoryItem: val=>dispatch(deleteReqHistoryItem(val))
})

export default connect(null, mapDispatchToProps)(ConsoleReqHistoryItem);
