// src/App/Pages/Console/ConsoleBody.vue
<template>
  <div class="console__body body console_block">
    <table class="body__table">
      <tbody>
        <tr>
          <ReqEditor />
          <ConsoleResize />
          <ResEditor />
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
  import ConsoleResize from './ConsoleResize'
  import ResEditor from './ResEditor.vue'
  import ReqEditor from './ReqEditor.vue'
  
  export default {
    components: {
      ConsoleResize,
      ResEditor,
      ReqEditor
    }
  }
</script>

// src/App/Components/Console/Body/ConsoleBody.jsx
import React from 'react';
import ConsoleResize from '../../UI/ConsoleResize';
import Table from '../../../hoc/Table';
import ResEditor from './ResEditor';
import ReqEditor from './ReqEditor';

const ConsoleBody = () => {

  return (
    <Table>
      <ReqEditor />
      <ConsoleResize />
      <ResEditor />
    </Table>
  );
}


export default ConsoleBody;
