// src/App/UI/ConsoleModalWindow.vue
<template>
  <div 
    v-if="item.title"
    :class="['console__modal', 'modal-window', 'modal-window_open', windowClose]" 
  >
    <div class="modal-window__wrapper">
      <h3 class="modal-window__title">{{item.title}}</h3>
      <div class="modal-window__button-group button-group"> 
        <Button 
          :title="'Удалить'"
          :classes="['button-danger']"
          @on-click="remove"
        />
        <Button 
          :title="'Отменить'"
          :classes="['button-cancel']"
          @on-click="closeWindow"
        />
      </div>
    </div>
    <button class="modal-window__close-button" @click="closeWindow">
      <svg class="icon modal-window__close-button-icon">
        <use xlink:href="/assets/icon/sprite.svg#times"></use>
      </svg>
    </button>
  </div>
</template>

<script>
  import Button from '@/UI/Button'
  import {mapState} from 'vuex'
  import ResHistory from '@/utils/ResHistory'

  export default {
    components: {Button},
    data() {
      return {
        windowClose: ''
      }
    },
    computed: mapState({
      item: state => state.modal
    }),
    methods: {
      closeWindow() {
        this.windowClose = 'modal-window_close';
        setTimeout(() => {
          this.$store.dispatch('closeModal');
          this.windowClose = '';
        }, 450);
      },
      remove() {
        if(this.item.actionId) {
          this.$store.dispatch('setReqHistoryData', ResHistory.deleteReqItemById(this.item.actionId));
        }else {
          this.$store.dispatch('setReqHistoryData', ResHistory.deleteAllHistoryItems());
        }
        this.closeWindow();
      },
      handleCLickOutside(e) {
        if (!this.$el?.contains(e.target)) {
          this.closeWindow();
        }
      },
      handleEscapeOutside(e) {
        if (e.key === 'Escape') {
          this.closeWindow();
        }
      }
    },
    updated() {      
      setTimeout(() => {
        if(!this.item.title) {
          document.removeEventListener("click", this.handleCLickOutside);
          document.removeEventListener("keydown", this.handleEscapeOutside);
        }else {
          document.addEventListener("click", this.handleCLickOutside);
          document.addEventListener("keydown", this.handleEscapeOutside);
        }
      }, 0);
    }
  }
</script>

// src/App/Components/Console/Body/ConsoleModalWindow.jsx
import React, { memo, useEffect, useRef, useState } from 'react';
import { connect } from 'react-redux';
import { closeModal } from '../../../Store/Action/consoleModal';
import { deleteHistory, deleteReqHistoryItem } from '../../../Store/Action/consoleReqHistory';
import Button from '../../UI/Button';

const shouldComponentUpdate  = (prev, next) => {
  return !!prev.modal.title === next.modal.title;
}

const ConsoleModalWindow = memo(props => {
  const item = props?.modal;
  if(!item.title) return null;
  const el = useRef();
  const [classes, setClasses] = useState(['console__modal', 'modal-window', 'modal-window_open']);

  const closeWindow = () =>{
    const openWindowClass = [...classes, 'modal-window_close'];
    setClasses(openWindowClass);
    setTimeout(() => {
      props.closeModal();
    }, 450);
    document.removeEventListener("click", handleCLickOutside);
    document.removeEventListener("keydown", handleEscapeOutside);
  }

  const remove = () => {
    if(item.actionId){
      props.deleteReqHistoryItem(item.actionId);
    }else {
      props.deleteHistory();
    }
    closeWindow();
  }

  const handleCLickOutside = e => {
    if (!el.current?.contains(e.target)) {
      closeWindow();
    }
  }

  const handleEscapeOutside = e => {
    if (e.key === 'Escape') {
      closeWindow();
    }
  }

  useEffect(()=>{
    document.addEventListener("click", handleCLickOutside);
    document.addEventListener("keydown", handleEscapeOutside);
  },[]);

  return (
    <div className={classes.join(' ')} ref={el}>
      <div className="modal-window__wrapper">
        <h3 className="modal-window__title">{item.title}</h3>
        <div className="modal-window__button-group button-group"> 
          <Button 
            title="Удалить"
            classes={["button-danger"]}
            onClick={()=>remove()}
          />
          <Button 
            title="Отменить"
            classes={["button-cancel"]}
            onClick={()=>closeWindow()}
          />
        </div>
      </div>
      <button className="modal-window__close-button" onClick={()=>closeWindow()}>
        <svg className="icon modal-window__close-button-icon">
          <use xlinkHref="/assets/icon/sprite.svg#times"></use>
        </svg>
      </button>
    </div>
  );
}, shouldComponentUpdate)

const mapStateToProps = state => ({
  modal: state.consoleModal.modal
})

const mapDispatchToProps = dispatch => ({
  closeModal: () => dispatch(closeModal()),
  deleteHistory: () => dispatch(deleteHistory()),
  deleteReqHistoryItem: id => dispatch(deleteReqHistoryItem(id))
})

export default connect(mapStateToProps, mapDispatchToProps)(ConsoleModalWindow);
