// src/App/Pages/Console/Components/ConsoleBody/Components/ResEditor.vue
<template>
  <ConsoleEditor 
    :name="'RES'"
    :title="'Ответ:'"
    :options="{
      showGutter: false,
      highlightActiveLine: false,
      printMargin: false,
      readOnly: true,
      showPrintMargin: false
    }"
    :content="content"
    :err="resErr"
  />
</template>

<script>
  import {mapState} from 'vuex'
  import ConsoleEditor from '@/UI/ConsoleEditor'

  export default {
    components: {ConsoleEditor},
    computed: mapState({
      content: state => {
        const {resData} = state.consoleRequest;
        
        if(Object.keys(resData)?.length){
          return JSON.stringify(resData, null, 2);
        }
        return "";
      },
      resErr: state => state.consoleRequest.resErr
    })
  }
</script>

// src/App/Components/Console/Body/ResEditor.jsx
import React from 'react';
import ConsoleEditor from '../../UI/ConsoleEditor';
import { useSelector } from 'react-redux';

const ResEditor = () => {
  const resData = useSelector(state => state.consoleRequest.resData);
  const resErr = useSelector(state => state.consoleRequest.resErr);

  const resDataVal = () => {
    if(Object.keys(resData)?.length){
      return JSON.stringify(resData, null, 2);
    }
    return "";
  }

  return (
    <ConsoleEditor 
      title="Ответ:"
      name="RES"
      value={resDataVal()}
      err={resErr}
      options={{
        showGutter: false,
        highlightActiveLine: false,
        printMargin: false,
        readOnly: true,
        showPrintMargin: false
      }}
    />
  );
}

export default ResEditor;
