// src/App/Components/UI/Button.jsx

import React from 'react';
import Loader from './Loader'

const Button = props => {
  const clickEvent = (e)=>{
    if(props.loading) return;
    e.preventDefault(); 
    props.onClick && props.onClick()
  }

  let classes = ['button'];
  if(props.classes?.length){
    classes = [classes, ...props.classes];
  }
  
  if(props.disabled) classes.push('button_disabled');
  else classes = classes.filter(el=>el!=='button_disabled');

  return (
    <button onClick={clickEvent} className={classes.join(' ')}>
      {
        props.loading ? 
          <Loader />
        : 
          <span className="button__text">{props.title}</span>
      }
    </button>
  );
}

export default Button;

// src/App/UI/Button.vue
<template>
  <button :class="classNames" @click="e => $emit('on-click', e)" >
    <Loader v-if="isLoad" />
    <span v-else class="button__text">{{title}}</span>
  </button>
</template>

<script>
  import Loader from './Loader'

  export default {
    components: {Loader},
    props: {
      disabled: Boolean,
      title: String,
      classes: Array,
      isLoad: Boolean
    },
    data(){
      return {
        classNames: ['button']
      }
    },
    watch: {
      disabled(disabled) {
        if(disabled) this.classNames = [...this.classNames, "button_disabled"];
        else this.classNames = this.classNames.filter(el => el !== "button_disabled");
      }
    },
    created() {
      if(this.classes?.length){
        this.classNames = [this.classNames, ...this.classes];
      }
    }
  }
</script>
