// src/App/Components/UI/ConsoleEditor.jsx
import React from 'react';
import AceEditor from "react-ace";

import "ace-builds/src-min-noconflict/mode-json";
import "ace-builds/src-min-noconflict/theme-github";

const ConsoleEditor = props => {

  return (
    <td className={`console__editor-wrap ${props.err && "console__editor-wrap_err" || ""}`}>
      <span className="console__editor-title">{props.title}</span>
      <div className="console__editor">
        <AceEditor
          mode="json"
          theme="github"
          name={props.name}
          value={props.value}
          width="100%"
          height="100%"
          setOptions={{
            ...props.options, 
            useWorker: false,
            fontSize: 14
          }}
          onChange={props.onChange}
        />
      </div>
    </td>
  );
}

export default ConsoleEditor;

// src/App/UI/ConsoleEditor.vue
<template>
  <td class="console__editor-wrap" :class="{'console__editor-wrap_err': err}">
    <span class="console__editor-title">{{title}}</span>
    <div class="console__editor">
      <div :id="name" style="width: 100%; height: 100%;"></div>
    </div>
  </td>
</template>

<script>
  import "ace-builds/src-min-noconflict/ace";

  export default {
    props: {
      name: String,
      content: String,
      title: String,
      options: Object,
      err: Boolean
    },
    data() {
      return {
        editor: Object
      }
    },
    watch: {
      content(val) {
        this.editor.setValue(val, 1);
      }
    },
    mounted() {  
      this.editor = window.ace.edit(this.name);
      const content = this.content || "";
      this.editor.setValue(content, -1);
      
      this.editor.getSession().setMode(`ace/mode/json`);
      this.editor.setTheme(`ace/theme/github`);

      this.editor.setOptions({
        ...this.options,
        useWorker: false,
        fontSize: 14
      })

      this.editor.on('change', () => {
        this.$emit('change-content', this.editor.getValue());
      })
    }
  }
</script>
