// src/App/Components/UI/MessageErr.jsx

import React from 'react';

const MessageErr = () => {
  return (
    <div className="message form__message">
      <div className="message__left-block">
        <svg className="icon icon_smile">
            <use xlinkHref="/assets/icon/sprite.svg#smile"></use>
        </svg>
      </div>
      <div className="message__right-block">
        <h4 className="h5 message__h5">Вход не вышел</h4>
        <p className="message__text">id: "error/auth/failed", explain: "wrong_credentials"</p>
      </div>
    </div>
  );
}

export default MessageErr;

// src/App/UI/MessageErr.vue
<template>
  <div class="message form__message">
    <div class="message__left-block">
      <svg class="icon icon_smile">
          <use xlinkHref="/assets/icon/sprite.svg#smile"></use>
      </svg>
    </div>
    <div class="message__right-block">
      <h4 class="h5 message__h5">Вход не вышел</h4>
      <p class="message__text">{{errMessage}}</p>
    </div>
  </div>
</template>

<script>
  export default {
    props: {
      errMessage: String
    }
  }
</script>
