// src/App/Components/UI/ReqDropCard.jsx
import React from 'react';

const ReqDropCard = () => {
  
  return (
    <ul className="console__req-drop-card req-drop-card">
      <li className="req-drop-card__item">Выполнить</li>
      <li className="req-drop-card__item">Скопировать</li>
      <li className="req-drop-card__item">Удалить</li>
    </ul>
  );
}

export default ReqDropCard;

// src/App/Pages/Console/Components/ConsoleReqHistory/ConsoleReqHistoryItem/Components/ReqDropCard.vue
<template>
  <ul class="console__req-drop-card req-drop-card">
    <li class="req-drop-card__item" >
      <span class="req-drop-card__text">Выполнить</span>
    </li>
    <li class="req-drop-card__item" >
      <span class="req-drop-card__text">Скопировать</span>
    </li>
    <li class="req-drop-card__item" >
      <span class="req-drop-card__text">Удалить</span>
    </li>
  </ul>
</template>
