// src/App/Components/ConsoleBody.jsx
import React from 'react';
import ConsoleResize from '../Components/UI/ConsoleResize';
import Table from '../hoc/Table';
import ConsoleEditor from './ConsoleEditor';

const ConsoleBody = () => {
  return (
    <Table>
      <ConsoleEditor
        title="Запрос:"
        name="REQ"
        options={{
          showGutter: false,
          highlightActiveLine: false,
          printMargin: false
        }}
      />
      <ConsoleResize />
      <ConsoleEditor 
        title="Ответ:"
        name="RES"
        options={{
          showGutter: false,
          highlightActiveLine: false,
          printMargin: false,
          readOnly: true,
          showPrintMargin: false
        }}
      />
    </Table>
  );
}

export default ConsoleBody;

// src/App/Pages/Console/Components/ConsoleBody/ConsoleBody.vue
<template>
  <div class="console__body body console_block">
    <table class="body__table">
      <tbody>
        <tr>
          <ConsoleEditor 
            :name="'REQ'"
            :title="'Запрос:'"
            :options="{
              showGutter: false,
              highlightActiveLine: false,
              printMargin: false
            }"
          />
          <ConsoleResize />
          <ConsoleEditor 
            :name="'RES'"
            :title="'Ответ:'"
            :options="{
              showGutter: false,
              highlightActiveLine: false,
              printMargin: false,
              readOnly: true,
              showPrintMargin: false
            }"
          />
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
  import ConsoleEditor from '@/UI/ConsoleEditor'
  import ConsoleResize from './ConsoleResize'
  
  export default {
    components: {ConsoleEditor, ConsoleResize}
  }
</script>
